baseurl: https://polina.io
disablePathToLower: true
languageCode: en-us
title: Polina Soshnin
author: Polina Soshnin
theme: orange
disableRSS: false
rssuri: atom.xml
author:
  name: Polina Soshnin
taxonomies:
  category: "categories"
...
